<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<!--

==== OUTPUT BEFORE FIX: ====
Start:201905121:161837.885

TC_001:TC Fix Me

Time to onTestFailure:201905121:161837.894

Time to onTestFailure:201905121:161837.894 // why printed twice? check org.testng.internal.Invoker.invokeMethod(...):
 org.testng.internal.Invoker.runTestListeners is called twice: line 559 and line 636.
java.lang.NullPointerException
    at se.ericsson.training.testng.exercise.FixMe.onTestFailure(FixMe.java:52)
    at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1042)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    at org.testng.TestRunner.privateRun(TestRunner.java:648)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    at org.testng.TestNG.runSuites(TestNG.java:1049)
    at org.testng.TestNG.run(TestNG.java:1017)
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

Process finished with exit code 255


==== OUTPUT AFTER FIX: ====

FixMe.testMe()[pri:0, instance:se.ericsson.training.testng.solution.FixMe@3c0ecd4b] - Start: 201905121_162031.748

TC_001:TC Fix Me

FixMe.testMe()[pri:0, instance:se.ericsson.training.testng.solution.FixMe@3c0ecd4b] - Time to onTestFailure: 201905121_162037.756

FixMe.testMe()[pri:0, instance:se.ericsson.training.testng.solution.FixMe@3c0ecd4b] - Duration (Solution 1) = 6008 milliseconds.

FixMe.testMe()[pri:0, instance:se.ericsson.training.testng.solution.FixMe@3c0ecd4b] - Duration (Solution 2) = 6007 milliseconds.


java.lang.AssertionError: expected [2] but found [3]
Expected :2
Actual   :3
 <Click to see difference>


    at org.testng.Assert.fail(Assert.java:96)
    at org.testng.Assert.failNotEquals(Assert.java:776)
    at org.testng.Assert.assertEqualsImpl(Assert.java:137)
    at org.testng.Assert.assertEquals(Assert.java:118)
    at org.testng.Assert.assertEquals(Assert.java:652)
    at org.testng.Assert.assertEquals(Assert.java:662)
    at se.ericsson.training.testng.solution.FixMe.testMe(FixMe.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    at org.testng.TestRunner.privateRun(TestRunner.java:648)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    at org.testng.TestNG.runSuites(TestNG.java:1049)
    at org.testng.TestNG.run(TestNG.java:1017)
    at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
    at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

-->
<suite name="Exercise Test Suite - FixMe">
    <test name="Test - FixMe">
        <classes>
            <class name="se.ericsson.training.testng.exercise.FixMe" />
            <!--<class name="se.ericsson.training.testng.solution.FixMe" />-->
        </classes>
    </test>
</suite>
